version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release_xp
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
build:
  project: build/III.VC.CLEO.sln
  verbosity: minimal
before_package:
- cmd: msbuild.exe build/CLEO_SDK.sln /t:Build /p:Configuration=Release_xp;Platform=Win32
after_build:
- cmd: pack_release.bat
artifacts:
- path: CLEO.III_v2.0.1.zip
  name: CLEO.III_v2.0.1.zip
- path: CLEO.VC_v2.0.1.zip
  name: CLEO.VC_v2.0.1.zip